name: Integrate

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  supported-ide-compatibility:
    name: Supported IDE compatibility
    uses: ./.github/workflows/_compatibility.yaml
    with:
      artifact: false
